engines:
  fixme:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD030:
        enabled: false
      MD013:
        code_blocks: false
        tables: false

ratings:
  paths:
    - "**.go"
    - "**.md"

exclude_paths: []
