engines:
  fixme:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
    code_blocks: false
    tables: false
    checks:
      MD030:
        enabled: false
ratings:
  paths:
    - "**.go"
    - "**.md"
exclude_paths: []
