before_script:
  - pwd
  - echo deb http://http.debian.net/debian jessie-backports main >> /etc/apt/sources.list
  - apt-get update -qq
  - apt-get install -y -qq openjdk-8-jre-headless tree
  - wget https://storage.googleapis.com/golang/go1.7.1.linux-amd64.tar.gz
  - tar -xvf go1.7.linux-amd64.tar.gz
  - mv go /usr/local

build:
  script:
    - export ORIGIN
    - mkdir -p ~/workspace/go/src/github.com/bpicode/fritzctl
    - cp -r . ~/workspace/go/src/github.com/bpicode/fritzctl
    - cd ~
    - export GOPATH=$(pwd)/workspace/go
    - export GOROOT=/usr/local/go
    - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
    - export FRITZCTL_VERSION=1.0.$(date +%Y%m%d%H%M)
    - cd workspace/go/src/github.com/bpicode/fritzctl
    - pwd
    - export GOOS=linux
    - export GOARCH=amd64
    - make clean all
    - ./gradlew -b packaging_build.gradle buildDeb
    - export GOOS=linux
    - export GOARCH=arm
    - go build -o $GOPATH/bin/fritzctl
    - ./gradlew -b packaging_build.gradle buildDeb
    - tree ~/workspace/go/src/github.com/bpicode/fritzctl/build/distributions/
    - cp -r ~/workspace/go/src/github.com/bpicode/fritzctl/build $CI_PROJECT_DIR
  artifacts:
    paths:
      - ./build/distributions/*.deb
      - ./build/distributions/*.rpm

