variables:
  GO_DIST: "go1.9.1.linux-amd64.tar.gz"
  FRITZCTL_VERSION: "1.4.16"

before_script:
  - pwd
  - apt-get update -qq
  - apt-get install -y -qq tree dpkg-sig curl zip ruby ruby-dev rubygems gcc make rpm
  - wget --quiet https://storage.googleapis.com/golang/$GO_DIST
  - tar -xf $GO_DIST
  - mv go /usr/local
  - gem install --no-ri --no-rdoc fpm
  - export PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"

after_script:
  - gpg --batch --delete-secret-and-public-keys --yes 0A56A1CE2DFCECA404A5C884E4598EE3D0E416CE

build:
  only:
    - web
  script:
    - export ORIGIN
    - mkdir -p ~/workspace/go/src/github.com/bpicode/fritzctl
    - cp -r . ~/workspace/go/src/github.com/bpicode/fritzctl
    - cd ~
    - export GOPATH=$(pwd)/workspace/go
    - export GOROOT=/usr/local/go
    - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

    - go version
    - fpm --version

    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - pwd

    - echo "$DEB_SIGNING_KEY_PRIVATE" | gpg --import

    - make clean all pkg_all sign_deb publish_all

    - gpg --batch --delete-secret-and-public-keys --yes 0A56A1CE2DFCECA404A5C884E4598EE3D0E416CE

    - cp -r $GOPATH/src/github.com/bpicode/fritzctl/build $CI_PROJECT_DIR    

  artifacts:
    name: fritzctl_v1.4.16_all
    paths:
      - ./build/distributions/*.deb
      - ./build/distributions/*.rpm
      - ./build/distributions/*.zip
