before_script:
  - pwd
  - echo deb http://http.debian.net/debian jessie-backports main >> /etc/apt/sources.list
  - apt-get update -qq
  - apt-get install -y -qq openjdk-8-jre-headless golang tree

build:
  script:
    - mkdir -p ~/workspace/go/src/github.com/bpicode/fritzctl
    - cp -r . ~/workspace/go/src/github.com/bpicode/fritzctl
    - cd ~
    - export GOPATH=$(pwd)/workspace/go
    - cd workspace/go/src/github.com/bpicode/fritzctl
    - pwd
    - make
    - ./gradlew -b packaging_build.gradle buildRpm buildDeb
    - tree ~/workspace/go/src/github.com/bpicode/
    - tree ~/workspace/go/src/github.com/bpicode/fritzctl/build/distributions/
  artifacts:
    paths:
      - /root/workspace/go/src/github.com/bpicode/fritzctl/build/distributions/*.deb
      - /root/workspace/go/src/github.com/bpicode/fritzctl/build/distributions/*.rpm
