variables:
  GO_DIST: "go1.9.2.linux-amd64.tar.gz"
  FRITZCTL_VERSION: "1.4.16"

before_script:
  - pwd
  - mkdir -p ~/go/src/github.com/bpicode/fritzctl
  - cp -r . ~/go/src/github.com/bpicode/fritzctl

  - apt-get update -qq
  - apt-get install -y -qq tree dpkg-sig curl zip ruby ruby-dev rubygems gcc make rpm

  - wget --quiet https://storage.googleapis.com/golang/$GO_DIST
  - tar -xf $GO_DIST
  - mv go /usr/local
  - cd ~
  - export GOPATH=$(pwd)/go
  - export GOROOT=/usr/local/go
  - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

  - gem install --no-ri --no-rdoc fpm
  - export PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"

  - echo "$DEB_SIGNING_KEY_PRIVATE" | gpg --import

  - export ORIGIN

after_script:
  - gpg --batch --delete-secret-and-public-keys --yes 0A56A1CE2DFCECA404A5C884E4598EE3D0E416CE

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean sysinfo deps build

test_job:
  stage: test
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean deps test

cq_job:
  stage: test
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean deps codequality

deploy_job:
  only:
    - tags
    - web
  stage: deploy
  script:
    - make clean deps pkg_all sign_deb publish_all
    - cp -r $GOPATH/src/github.com/bpicode/fritzctl/build $CI_PROJECT_DIR
  artifacts:
      name: fritzctl_v1.4.16_all
      paths:
        - ./build/distributions/fritzctl*
