before_script:
  - pwd
  - echo deb http://http.debian.net/debian jessie-backports main >> /etc/apt/sources.list
  - apt-get update -qq

build:
  script:
    - mkdir -p workspace/go/src/github.com/bpicode/fritzctl
    - cp -r . workspace/go/src/github.com/bpicode/fritzctl
    - export GOPATH=$(pwd)/workspace/go
    - cd workspace/go/src/github.com/bpicode/fritzctl
    - make
    - ./gradlew -b packaging_build.gradle buildRpm buildDeb
  artifacts:
    paths:
      - ./build/distributions/*.deb
      - ./build/distributions/*.rpm
