before_script:
  - pwd
  - echo deb http://http.debian.net/debian jessie-backports main >> /etc/apt/sources.list
  - apt-get update -qq
  - apt-get install -y -qq openjdk-8-jre-headless tree dpkg-sig curl
  - wget --quiet https://storage.googleapis.com/golang/go1.7.1.linux-amd64.tar.gz
  - tar -xf go1.7.1.linux-amd64.tar.gz
  - mv go /usr/local

build:
  script:
    - export ORIGIN
    - mkdir -p ~/workspace/go/src/github.com/bpicode/fritzctl
    - cp -r . ~/workspace/go/src/github.com/bpicode/fritzctl
    - cd ~
    - export GOPATH=$(pwd)/workspace/go
    - export GOROOT=/usr/local/go
    - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
    - export FRITZCTL_VERSION=1.1.$(date +%Y%m%d%H%M)
    - cd workspace/go/src/github.com/bpicode/fritzctl
    - pwd
    - export GOOS=linux
    - export GOARCH=amd64
    - make clean all
    - ./gradlew -b packaging_build.gradle buildDeb buildRpm
    - export GOOS=linux
    - export GOARCH=arm
    - go build -o $GOPATH/bin/fritzctl
    - ./gradlew -b packaging_build.gradle buildDeb buildRpm
    - tree ~/workspace/go/src/github.com/bpicode/fritzctl/build/distributions/
    - cp -r ~/workspace/go/src/github.com/bpicode/fritzctl/build $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR/build/distributions
    - echo "$DEB_SIGNING_KEY_PUBLIC" | gpg --import
    - echo "$DEB_SIGNING_KEY_PRIVATE" | gpg --import
    - dpkg-sig --sign origin -k D0E416CE --g "--no-tty --passphrase=$DEB_SIGNING_KEY_PASSWORD" *.deb
    - dpkg-sig --verify *.deb
    - gpg --batch --delete-secret-and-public-keys --yes 0A56A1CE2DFCECA404A5C884E4598EE3D0E416CE
    - AMD64DEB=$(ls fritzctl_*_amd64.deb)
    - ARMDEB=$(ls fritzctl_*_arm.deb)
    - echo "Uploading $AMD64DEB to bintray"
    - curl -f -T $AMD64DEB -ubpicode:$BINTRAY_API_KEY  -H "X-GPG-PASSPHRASE:$BINTRAY_SIGN_GPG_PASSPHRASE" "https://api.bintray.com/content/bpicode/fritzctl_deb/fritzctl/$FRITZCTL_VERSION/pool/main/m/fritzctl/$AMD64DEB;deb_distribution=wheezy,jessie;deb_component=main;deb_architecture=amd64;publish=1"
    - curl -f -T $ARMDEB -ubpicode:$BINTRAY_API_KEY  -H "X-GPG-PASSPHRASE:$BINTRAY_SIGN_GPG_PASSPHRASE" "https://api.bintray.com/content/bpicode/fritzctl_deb/fritzctl/$FRITZCTL_VERSION/pool/main/m/fritzctl/$ARMDEB;deb_distribution=wheezy,jessie;deb_component=main;deb_architecture=arm;publish=1"
    - curl -f -X POST -H "X-GPG-PASSPHRASE:$BINTRAY_SIGN_GPG_PASSPHRASE" -ubpicode:$BINTRAY_API_KEY https://api.bintray.com/calc_metadata/bpicode/fritzctl_deb
    - AMD64RPM=$(ls fritzctl-*.x86_64.rpm)
    - ARMRPM=$(ls fritzctl-*.arm.rpm)
    - echo "Uploading $AMD64RPM to bintray"
    - curl -f -T $AMD64RPM -ubpicode:$BINTRAY_API_KEY  -H "X-GPG-PASSPHRASE:$BINTRAY_SIGN_GPG_PASSPHRASE" "https://api.bintray.com/content/bpicode/fritzctl_rpm/fritzctl/$FRITZCTL_VERSION/$AMD64RPM;publish=1"
    - echo "Uploading $ARMRPM to bintray"
    - curl -f -T $ARMRPM -ubpicode:$BINTRAY_API_KEY  -H "X-GPG-PASSPHRASE:$BINTRAY_SIGN_GPG_PASSPHRASE" "https://api.bintray.com/content/bpicode/fritzctl_rpm/fritzctl/$FRITZCTL_VERSION/$ARMRPM;publish=1"    
    - curl -f -X POST -H "X-GPG-PASSPHRASE:$BINTRAY_SIGN_GPG_PASSPHRASE" -ubpicode:$BINTRAY_API_KEY https://api.bintray.com/calc_metadata/bpicode/fritzctl_rpm


  artifacts:
    paths:
      - ./build/distributions/*.deb
      - ./build/distributions/*.rpm
