image: bpicode/docker_golang

variables:
  GO_DIST: "go1.9.2.linux-amd64.tar.gz"
  FRITZCTL_VERSION: "1.4.17"

before_script:
  - pwd
  - mkdir -p ~/go/src/github.com/bpicode/fritzctl
  - cp -r . ~/go/src/github.com/bpicode/fritzctl

  - echo "$DEB_SIGNING_KEY_PRIVATE" | gpg --import

  - export ORIGIN

after_script:
  - gpg --batch --delete-secret-and-public-keys --yes 0A56A1CE2DFCECA404A5C884E4598EE3D0E416CE

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean sysinfo deps build

test_job:
  stage: test
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean deps test

cq_job:
  stage: test
  script:
    - cd $GOPATH/src/github.com/bpicode/fritzctl
    - make clean deps codequality

deploy_job:
  only:
    - tags
    - web
  stage: deploy
  script:
    - make clean deps pkg_all sign_deb publish_all
    - cp -r $GOPATH/src/github.com/bpicode/fritzctl/build $CI_PROJECT_DIR
  artifacts:
      name: fritzctl_v1.4.17_all
      paths:
        - ./build/distributions/fritzctl*
