version: "0.0.1-{build}-unofficial-ci-appveyor"

clone_folder: c:\gopath\src\github.com\bpicode\fritzctl

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

build_script:
  - go build

test_script:
  - go test -race ./...
