version: "1.3.0-{build}"

clone_folder: c:\gopath\src\github.com\bpicode\fritzctl

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go build

test_script:
  - go test -race ./...