[[constraint]]
  name = "github.com/cpuguy83/go-md2man"
  version = "1.0.6"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"


# Below are fixes for stuff that dep did wrong

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "93622da34e54fb6529bfb7c57e710f37a8d9cbd8"
