name: Continuous Integration
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILDFLAGS: -ldflags="-X github.com/bpicode/fritzctl/config.Version=undefined -X github.com/bpicode/fritzctl/config.Revision=${{ github.sha }}"

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Environment information
      run: |
        echo "UNAME: $(uname -a)"
        echo "PWD: $(pwd)"
        echo "PATH: ${PATH}"
        echo "GO: $(go version)"
        echo "GO ENV: $(go env)"
        echo "BUILDFLAGS: ${BUILDFLAGS}"

    - name: Build
      run: go build "${BUILDFLAGS}" -v

    - name: Test
      run: go test "${BUILDFLAGS}" -run '(Test|Example)' -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Verify dependencies have expected content
      run: go mod verify
    
    - name: Install code quality tools
      env:
        GO111MODULE: off
        GOBIN: /usr/local/bin
      run: |
        sudo go get -u github.com/mgechev/revive
        sudo go get -u github.com/fzipp/gocyclo
        sudo go get -u golang.org/x/lint/golint
        sudo go get -u github.com/gordonklaus/ineffassign
        sudo go get -u github.com/client9/misspell/cmd/misspell
        sudo go get -u honnef.co/go/tools/cmd/staticcheck
        sudo go get -u github.com/mdempsky/unconvert

    - name: Code quality (revive)
      run: revive -formatter friendly -exclude vendor/... ./...

    - name: Code quality (formatting)
      run: (gofmt -s -l -d -e $(find . -type f -name '*.go' -not -path "./vendor/*") | tee /dev/stderr) || exit 1;

    - name: Code quality (vet)
      run: go vet ./...

    - name: Code quality (bounded cyclomatic complexity)
      run: gocyclo -over 15 $(find . -type f -name '*.go' -not -path "./vendor/*")

    - name: Code quality (golint style mistakes)
      run: golint -set_exit_status $(go list ./...)

    - name: Code quality (detect ineffectual assignments)
      run: ineffassign .

    - name: Code quality (spelling mistakes)
      run: misspell --error $(find . -type f -not -path "./vendor/*" -not -path "./.git/*")

    - name: Code quality (bugs, suggest code simplifications, point out dead code, and more)
      run: staticcheck -checks=all ./...

    - name: Code quality (identify unnecessary type conversions)
      run: unconvert -v ./...
